version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: events-app
    expose:
      - 9000
    volumes:
      - '.:/var/www'
    networks:
      - events-net
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: events-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - events-net
  nginx:
    image: nginx:alpine
    container_name: events-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - events-net

networks:
  events-net:
    driver: bridge